Remove unused variable which caused compile error
ERROR:
Was Item old;
falcon/engine/psteps/exprcall.cpp:109:24: error: variable ‘old’ set but not used [-Werror=unused-but-set-variable]